data_root: /projects/PUCHALLA/LLP2024/tumor/data
mmconfig_path: /projects/PUCHALLA/LLP2024/tumor/sensaug/custom_configs/mmseg
primary_metric: mIoU
datasets:
  cityscapes: cityscapes
supported_backbones:
  - pspnet
  - segformer
  - convnext
  - deeplabv3plus
  - swin
  - mae
  - vit
